name: server-ci
on: 
  pull_request:
    branches:
      - main

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Install Docker
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Docker Push
          uses: docker/build-push-action@v6
          with:
            context: server
            file: server/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/lets-chat-server:${{ github.run_id }}
            build-args: |
              FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
              FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
              FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
              FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
              FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
              FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
              GENERATE_SOURCEMAP=false
              AZURE_SQL_CONNECTION_STRING=${{ secrets.AZURE_SQL_CONNECTION_STRING }}

    updatek8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

        - name: Update tag in kubernetes deployment manifest
          run: | 
               sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/lets-chat-server:${{ github.run_id }}|" K8s/server-deployment.yaml
        
        - name: Commit and push changes
          run: |
            git config --global user.email "pranayjujjuri@gmail.com"
            git config --global user.name "Pranay Jujjuri"
            git add K8s/server-deployment.yaml
            git commit -m "[CI]: Update frontend image tag"
            git push origin HEAD:${{ github.head_ref }} -f
        
